
# general configuration
spring:
 jpa:
  databasePlatform: org.hibernate.dialect.H2Dialect
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:

# h2 configuration
 h2:
  console:
   enabled: true 
   path: /h2  

#docs
springdoc:
 api-docs:
  path: /api-docs